Blog app - integration specs for views and fix n+1 problems
apt2tell/blog-app pull request #8
Opened 2023-01-31 20:37 UTC by Okechukwu-muokwugwo

## Writing integration tests with Capybara gem and securing app from `n+1` problems.

> I and @Baayeh accomplished the following tasks in this features:

- Solved the `N+1` problem for the posts#index
- Implement test case for user show view
- Implement test case for post show view
- Add integration test case for User index page
- Add test case for User post index page

before:
![post_query_before](https://user-images.githubusercontent.com/111280966/215876830-0de36b3d-6880-4b6b-ab36-675449f0214d.PNG)

after:
![post_query_after](https://user-images.githubusercontent.com/111280966/215876875-851a191a-97e4-4d67-8958-653de21286d6.PNG)

2023-01-31 21:07 UTC, GzimAsani requested changes
### Hello @Okechukwu-muokwugwo and @Baayeh                          :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your testing, I really like how you tested them and you did 95% of the job, just few more things left +1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 
- _**If you are struggling with tests, use this [capybara cheat sheet](https://gist.github.com/zhengjia/428105)**_


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 21:07 UTC, GzimAsani commented on spec/integration/post_index_spec.rb
> +    it 'has first comments on a post' do
- [ ] You have two failing tests kindly update them 
![image](https://user-images.githubusercontent.com/62705947/215880265-a5f9afd5-13e7-45d2-816b-9d0ed1f11c67.png)

2023-01-31 23:24 UTC, Whoistolu requested changes
Hi @Okechukwu-muokwugwo 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 23:24 UTC, Whoistolu commented on spec/integration/post_index_spec.rb
> +end
- [ ] [REQUIRED] It looks like the previous reviewer missed out on this. Kindly note that  a part of the requirement states that you must have a featured test for `User` **post index page**:
- Tests that assert you can see how many likes a post has.

Kindly add this test as it is a core requirement.

2023-01-31 23:24 UTC, Whoistolu commented on spec/integration/post_index_spec.rb
> +    it 'has first comments on a post' do
- Well resolved @Okechukwu-muokwugwo 👍🏽

2023-02-01 00:16 UTC, andersonlebon approved these changes
## Hi @Okechukwu-muokwugwo  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 07:32 UTC, merged