Blog app: add devise
apt2tell/blog-app pull request #9
Opened 2023-02-01 15:43 UTC by Okechukwu-muokwugwo

## Building a web app that requires the user to log in and using devise gem for authentication.

> I and @Baayeh accomplished the following in this branch:

- Installed and set up `devise`
- Configured `blog-app` to allow to: 
     >  register a new user.
      > User logs in with a combination of email and password.
      > Hashed password should be stored in the database.
      > Ask for confirmation of email.
      > Can reset password.

2023-02-01 16:05 UTC, GzimAsani requested changes
### Hello @Okechukwu-muokwugwo and @Baayeh                        :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your devise, most of the work is done :+1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 


 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 16:05 UTC, GzimAsani commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] The application needs ti asks for confirmation of email. Here you need to add also :`confirmable`. Please do that

2023-02-01 16:05 UTC, GzimAsani commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] A user can reset the password in the application, currently I am getting an error when I try to do that
![image](https://user-images.githubusercontent.com/62705947/216093904-33e0d213-c15d-4b75-b2ce-7e3344d69327.png)

2023-02-01 16:05 UTC, GzimAsani commented on config/initializers/devise.rb
> +  # confirming their account. For instance, if set to 2.days, the user will be
- This is for readme, please update only these changes 
![image](https://user-images.githubusercontent.com/62705947/216094608-b09d73f9-2eff-4e9c-8dbf-df5012e263ab.png)

2023-02-02 11:53 UTC, Lucas-Masaba approved these changes
# Hello @Okechukwu-muokwugwo  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- Made changes as requested by the previous reviewer 👍 
- Well-written commit messages 🏄 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 12:06 UTC, merged